// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   int32                  `protobuf:"varint,1,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	Players       map[string]*Player     `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Started       bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Galaxy        *GalaxyState           `protobuf:"bytes,4,opt,name=galaxy,proto3" json:"galaxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *JoinResponse) GetPlayers() map[string]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *JoinResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *JoinResponse) GetGalaxy() *GalaxyState {
	if x != nil {
		return x.Galaxy
	}
	return nil
}

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type System struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Fleets        []*Fleet               `protobuf:"bytes,5,rep,name=fleets,proto3" json:"fleets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *System) Reset() {
	*x = System{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *System) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *System) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *System) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *System) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *System) GetFleets() []*Fleet {
	if x != nil {
		return x.Fleets
	}
	return nil
}

type GalaxyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Systems       []*System              `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GalaxyState) Reset() {
	*x = GalaxyState{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GalaxyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GalaxyState) ProtoMessage() {}

func (x *GalaxyState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GalaxyState.ProtoReflect.Descriptor instead.
func (*GalaxyState) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *GalaxyState) GetSystems() []*System {
	if x != nil {
		return x.Systems
	}
	return nil
}

func (x *GalaxyState) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GalaxyState) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   int32                  `protobuf:"varint,1,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	Players       map[string]*Player     `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Started       bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *GameState) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *GameState) GetPlayers() map[string]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

type GameUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   int32                  `protobuf:"varint,1,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	Players       map[string]*Player     `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Started       bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Galaxy        *GalaxyState           `protobuf:"bytes,4,opt,name=galaxy,proto3" json:"galaxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdate) Reset() {
	*x = GameUpdate{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdate) ProtoMessage() {}

func (x *GameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdate.ProtoReflect.Descriptor instead.
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *GameUpdate) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *GameUpdate) GetPlayers() map[string]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameUpdate) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *GameUpdate) GetGalaxy() *GalaxyState {
	if x != nil {
		return x.Galaxy
	}
	return nil
}

type Fleet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Attack        int32                  `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty"`
	Health        int32                  `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,5,opt,name=maxHealth,proto3" json:"maxHealth,omitempty"`
	LastMovedTick int32                  `protobuf:"varint,6,opt,name=lastMovedTick,proto3" json:"lastMovedTick,omitempty"`
	Evasion       int32                  `protobuf:"varint,7,opt,name=evasion,proto3" json:"evasion,omitempty"` // out of 100
	Armor         int32                  `protobuf:"varint,8,opt,name=armor,proto3" json:"armor,omitempty"`     // out of 100
	Exattack      int32                  `protobuf:"varint,9,opt,name=exattack,proto3" json:"exattack,omitempty"`
	// ship counts
	Composition   *FleetComposition `protobuf:"bytes,10,opt,name=composition,proto3" json:"composition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fleet) Reset() {
	*x = Fleet{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet) ProtoMessage() {}

func (x *Fleet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleet.ProtoReflect.Descriptor instead.
func (*Fleet) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *Fleet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fleet) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Fleet) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *Fleet) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Fleet) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Fleet) GetLastMovedTick() int32 {
	if x != nil {
		return x.LastMovedTick
	}
	return 0
}

func (x *Fleet) GetEvasion() int32 {
	if x != nil {
		return x.Evasion
	}
	return 0
}

func (x *Fleet) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *Fleet) GetExattack() int32 {
	if x != nil {
		return x.Exattack
	}
	return 0
}

func (x *Fleet) GetComposition() *FleetComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

type FleetComposition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destroyers    int32                  `protobuf:"varint,1,opt,name=destroyers,proto3" json:"destroyers,omitempty"`
	Cruisers      int32                  `protobuf:"varint,2,opt,name=cruisers,proto3" json:"cruisers,omitempty"`
	Battleships   int32                  `protobuf:"varint,3,opt,name=battleships,proto3" json:"battleships,omitempty"`
	Dreadnoughts  int32                  `protobuf:"varint,4,opt,name=dreadnoughts,proto3" json:"dreadnoughts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetComposition) Reset() {
	*x = FleetComposition{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetComposition) ProtoMessage() {}

func (x *FleetComposition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetComposition.ProtoReflect.Descriptor instead.
func (*FleetComposition) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *FleetComposition) GetDestroyers() int32 {
	if x != nil {
		return x.Destroyers
	}
	return 0
}

func (x *FleetComposition) GetCruisers() int32 {
	if x != nil {
		return x.Cruisers
	}
	return 0
}

func (x *FleetComposition) GetBattleships() int32 {
	if x != nil {
		return x.Battleships
	}
	return 0
}

func (x *FleetComposition) GetDreadnoughts() int32 {
	if x != nil {
		return x.Dreadnoughts
	}
	return 0
}

// UDP TYPES, NOT USED FOR TCP GRPC
type TickMsg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FleetMovements     []*FleetMovement       `protobuf:"bytes,2,rep,name=fleetMovements,proto3" json:"fleetMovements,omitempty"`
	HealthUpdates      []*HealthUpdate        `protobuf:"bytes,3,rep,name=healthUpdates,proto3" json:"healthUpdates,omitempty"`
	FleetDestroyed     []*FleetDestroyed      `protobuf:"bytes,4,rep,name=fleetDestroyed,proto3" json:"fleetDestroyed,omitempty"`
	SystemOwnerChanges []*SystemOwnerChange   `protobuf:"bytes,5,rep,name=systemOwnerChanges,proto3" json:"systemOwnerChanges,omitempty"`
	GesUpdates         []*GESUpdate           `protobuf:"bytes,6,rep,name=gesUpdates,proto3" json:"gesUpdates,omitempty"`
	FleetCreations     []*FleetCreation       `protobuf:"bytes,7,rep,name=fleetCreations,proto3" json:"fleetCreations,omitempty"`
	FleetModifications []*FleetModification   `protobuf:"bytes,8,rep,name=fleetModifications,proto3" json:"fleetModifications,omitempty"`
	FleetUpdates       []*FleetUpdate         `protobuf:"bytes,9,rep,name=fleetUpdates,proto3" json:"fleetUpdates,omitempty"`
	Victory            *GameVictory           `protobuf:"bytes,10,opt,name=victory,proto3" json:"victory,omitempty"`
	TickCount          int32                  `protobuf:"varint,11,opt,name=tickCount,proto3" json:"tickCount,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TickMsg) Reset() {
	*x = TickMsg{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMsg) ProtoMessage() {}

func (x *TickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMsg.ProtoReflect.Descriptor instead.
func (*TickMsg) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *TickMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TickMsg) GetFleetMovements() []*FleetMovement {
	if x != nil {
		return x.FleetMovements
	}
	return nil
}

func (x *TickMsg) GetHealthUpdates() []*HealthUpdate {
	if x != nil {
		return x.HealthUpdates
	}
	return nil
}

func (x *TickMsg) GetFleetDestroyed() []*FleetDestroyed {
	if x != nil {
		return x.FleetDestroyed
	}
	return nil
}

func (x *TickMsg) GetSystemOwnerChanges() []*SystemOwnerChange {
	if x != nil {
		return x.SystemOwnerChanges
	}
	return nil
}

func (x *TickMsg) GetGesUpdates() []*GESUpdate {
	if x != nil {
		return x.GesUpdates
	}
	return nil
}

func (x *TickMsg) GetFleetCreations() []*FleetCreation {
	if x != nil {
		return x.FleetCreations
	}
	return nil
}

func (x *TickMsg) GetFleetModifications() []*FleetModification {
	if x != nil {
		return x.FleetModifications
	}
	return nil
}

func (x *TickMsg) GetFleetUpdates() []*FleetUpdate {
	if x != nil {
		return x.FleetUpdates
	}
	return nil
}

func (x *TickMsg) GetVictory() *GameVictory {
	if x != nil {
		return x.Victory
	}
	return nil
}

func (x *TickMsg) GetTickCount() int32 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

type FleetModification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       int32                  `protobuf:"varint,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	SystemId      int32                  `protobuf:"varint,2,opt,name=systemId,proto3" json:"systemId,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Composition   *FleetComposition      `protobuf:"bytes,4,opt,name=composition,proto3" json:"composition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetModification) Reset() {
	*x = FleetModification{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetModification) ProtoMessage() {}

func (x *FleetModification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetModification.ProtoReflect.Descriptor instead.
func (*FleetModification) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *FleetModification) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *FleetModification) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *FleetModification) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FleetModification) GetComposition() *FleetComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

type FleetMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       int32                  `protobuf:"varint,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	FromSystemId  int32                  `protobuf:"varint,2,opt,name=fromSystemId,proto3" json:"fromSystemId,omitempty"`
	ToSystemId    int32                  `protobuf:"varint,3,opt,name=toSystemId,proto3" json:"toSystemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetMovement) Reset() {
	*x = FleetMovement{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMovement) ProtoMessage() {}

func (x *FleetMovement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMovement.ProtoReflect.Descriptor instead.
func (*FleetMovement) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *FleetMovement) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *FleetMovement) GetFromSystemId() int32 {
	if x != nil {
		return x.FromSystemId
	}
	return 0
}

func (x *FleetMovement) GetToSystemId() int32 {
	if x != nil {
		return x.ToSystemId
	}
	return 0
}

type HealthUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       int32                  `protobuf:"varint,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Health        int32                  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	SystemId      int32                  `protobuf:"varint,3,opt,name=systemId,proto3" json:"systemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthUpdate) Reset() {
	*x = HealthUpdate{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthUpdate) ProtoMessage() {}

func (x *HealthUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthUpdate.ProtoReflect.Descriptor instead.
func (*HealthUpdate) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *HealthUpdate) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *HealthUpdate) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *HealthUpdate) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type FleetUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       int32                  `protobuf:"varint,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	SystemId      int32                  `protobuf:"varint,2,opt,name=systemId,proto3" json:"systemId,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,3,opt,name=maxHealth,proto3" json:"maxHealth,omitempty"`
	Health        int32                  `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Attack        int32                  `protobuf:"varint,5,opt,name=attack,proto3" json:"attack,omitempty"`
	Evasion       int32                  `protobuf:"varint,6,opt,name=evasion,proto3" json:"evasion,omitempty"`
	Armor         int32                  `protobuf:"varint,7,opt,name=armor,proto3" json:"armor,omitempty"`
	Exattack      int32                  `protobuf:"varint,8,opt,name=exattack,proto3" json:"exattack,omitempty"`
	Composition   *FleetComposition      `protobuf:"bytes,9,opt,name=composition,proto3" json:"composition,omitempty"`
	Owner         string                 `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetUpdate) Reset() {
	*x = FleetUpdate{}
	mi := &file_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetUpdate) ProtoMessage() {}

func (x *FleetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetUpdate.ProtoReflect.Descriptor instead.
func (*FleetUpdate) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *FleetUpdate) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *FleetUpdate) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *FleetUpdate) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *FleetUpdate) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *FleetUpdate) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *FleetUpdate) GetEvasion() int32 {
	if x != nil {
		return x.Evasion
	}
	return 0
}

func (x *FleetUpdate) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *FleetUpdate) GetExattack() int32 {
	if x != nil {
		return x.Exattack
	}
	return 0
}

func (x *FleetUpdate) GetComposition() *FleetComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *FleetUpdate) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type FleetDestroyed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       int32                  `protobuf:"varint,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	SystemId      int32                  `protobuf:"varint,2,opt,name=systemId,proto3" json:"systemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetDestroyed) Reset() {
	*x = FleetDestroyed{}
	mi := &file_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetDestroyed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetDestroyed) ProtoMessage() {}

func (x *FleetDestroyed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetDestroyed.ProtoReflect.Descriptor instead.
func (*FleetDestroyed) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *FleetDestroyed) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *FleetDestroyed) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SystemOwnerChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      int32                  `protobuf:"varint,1,opt,name=systemId,proto3" json:"systemId,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemOwnerChange) Reset() {
	*x = SystemOwnerChange{}
	mi := &file_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemOwnerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemOwnerChange) ProtoMessage() {}

func (x *SystemOwnerChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemOwnerChange.ProtoReflect.Descriptor instead.
func (*SystemOwnerChange) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *SystemOwnerChange) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemOwnerChange) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type GESUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Rate          int32                  `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GESUpdate) Reset() {
	*x = GESUpdate{}
	mi := &file_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GESUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GESUpdate) ProtoMessage() {}

func (x *GESUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GESUpdate.ProtoReflect.Descriptor instead.
func (*GESUpdate) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *GESUpdate) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GESUpdate) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GESUpdate) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type FleetCreation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      int32                  `protobuf:"varint,1,opt,name=systemId,proto3" json:"systemId,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FleetId       int32                  `protobuf:"varint,3,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Attack        int32                  `protobuf:"varint,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	Evasion       int32                  `protobuf:"varint,6,opt,name=evasion,proto3" json:"evasion,omitempty"`
	Armor         int32                  `protobuf:"varint,7,opt,name=armor,proto3" json:"armor,omitempty"`
	Exattack      int32                  `protobuf:"varint,8,opt,name=exattack,proto3" json:"exattack,omitempty"`
	Composition   *FleetComposition      `protobuf:"bytes,9,opt,name=composition,proto3" json:"composition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetCreation) Reset() {
	*x = FleetCreation{}
	mi := &file_proto_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetCreation) ProtoMessage() {}

func (x *FleetCreation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetCreation.ProtoReflect.Descriptor instead.
func (*FleetCreation) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *FleetCreation) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *FleetCreation) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FleetCreation) GetFleetId() int32 {
	if x != nil {
		return x.FleetId
	}
	return 0
}

func (x *FleetCreation) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *FleetCreation) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *FleetCreation) GetEvasion() int32 {
	if x != nil {
		return x.Evasion
	}
	return 0
}

func (x *FleetCreation) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *FleetCreation) GetExattack() int32 {
	if x != nil {
		return x.Exattack
	}
	return 0
}

func (x *FleetCreation) GetComposition() *FleetComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

type GameVictory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winner        string                 `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameVictory) Reset() {
	*x = GameVictory{}
	mi := &file_proto_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameVictory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameVictory) ProtoMessage() {}

func (x *GameVictory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameVictory.ProtoReflect.Descriptor instead.
func (*GameVictory) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{20}
}

func (x *GameVictory) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"\a\n" +
	"\x05Empty\")\n" +
	"\vJoinRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xfd\x01\n" +
	"\fJoinResponse\x12 \n" +
	"\vplayerCount\x18\x01 \x01(\x05R\vplayerCount\x12:\n" +
	"\aplayers\x18\x02 \x03(\v2 .proto.JoinResponse.PlayersEntryR\aplayers\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\x12*\n" +
	"\x06galaxy\x18\x04 \x01(\v2\x12.proto.GalaxyStateR\x06galaxy\x1aI\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.proto.PlayerR\x05value:\x028\x01\"/\n" +
	"\x11ConnectionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x1c\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"p\n" +
	"\x06System\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12$\n" +
	"\x06fleets\x18\x05 \x03(\v2\f.proto.FleetR\x06fleets\"d\n" +
	"\vGalaxyState\x12'\n" +
	"\asystems\x18\x01 \x03(\v2\r.proto.SystemR\asystems\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\xcb\x01\n" +
	"\tGameState\x12 \n" +
	"\vplayerCount\x18\x01 \x01(\x05R\vplayerCount\x127\n" +
	"\aplayers\x18\x02 \x03(\v2\x1d.proto.GameState.PlayersEntryR\aplayers\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\x1aI\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.proto.PlayerR\x05value:\x028\x01\"\xf9\x01\n" +
	"\n" +
	"GameUpdate\x12 \n" +
	"\vplayerCount\x18\x01 \x01(\x05R\vplayerCount\x128\n" +
	"\aplayers\x18\x02 \x03(\v2\x1e.proto.GameUpdate.PlayersEntryR\aplayers\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\x12*\n" +
	"\x06galaxy\x18\x04 \x01(\v2\x12.proto.GalaxyStateR\x06galaxy\x1aI\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.proto.PlayerR\x05value:\x028\x01\"\xa8\x02\n" +
	"\x05Fleet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x16\n" +
	"\x06attack\x18\x03 \x01(\x05R\x06attack\x12\x16\n" +
	"\x06health\x18\x04 \x01(\x05R\x06health\x12\x1c\n" +
	"\tmaxHealth\x18\x05 \x01(\x05R\tmaxHealth\x12$\n" +
	"\rlastMovedTick\x18\x06 \x01(\x05R\rlastMovedTick\x12\x18\n" +
	"\aevasion\x18\a \x01(\x05R\aevasion\x12\x14\n" +
	"\x05armor\x18\b \x01(\x05R\x05armor\x12\x1a\n" +
	"\bexattack\x18\t \x01(\x05R\bexattack\x129\n" +
	"\vcomposition\x18\n" +
	" \x01(\v2\x17.proto.FleetCompositionR\vcomposition\"\x94\x01\n" +
	"\x10FleetComposition\x12\x1e\n" +
	"\n" +
	"destroyers\x18\x01 \x01(\x05R\n" +
	"destroyers\x12\x1a\n" +
	"\bcruisers\x18\x02 \x01(\x05R\bcruisers\x12 \n" +
	"\vbattleships\x18\x03 \x01(\x05R\vbattleships\x12\"\n" +
	"\fdreadnoughts\x18\x04 \x01(\x05R\fdreadnoughts\"\xe3\x04\n" +
	"\aTickMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12<\n" +
	"\x0efleetMovements\x18\x02 \x03(\v2\x14.proto.FleetMovementR\x0efleetMovements\x129\n" +
	"\rhealthUpdates\x18\x03 \x03(\v2\x13.proto.HealthUpdateR\rhealthUpdates\x12=\n" +
	"\x0efleetDestroyed\x18\x04 \x03(\v2\x15.proto.FleetDestroyedR\x0efleetDestroyed\x12H\n" +
	"\x12systemOwnerChanges\x18\x05 \x03(\v2\x18.proto.SystemOwnerChangeR\x12systemOwnerChanges\x120\n" +
	"\n" +
	"gesUpdates\x18\x06 \x03(\v2\x10.proto.GESUpdateR\n" +
	"gesUpdates\x12<\n" +
	"\x0efleetCreations\x18\a \x03(\v2\x14.proto.FleetCreationR\x0efleetCreations\x12H\n" +
	"\x12fleetModifications\x18\b \x03(\v2\x18.proto.FleetModificationR\x12fleetModifications\x126\n" +
	"\ffleetUpdates\x18\t \x03(\v2\x12.proto.FleetUpdateR\ffleetUpdates\x12,\n" +
	"\avictory\x18\n" +
	" \x01(\v2\x12.proto.GameVictoryR\avictory\x12\x1c\n" +
	"\ttickCount\x18\v \x01(\x05R\ttickCount\"\x9a\x01\n" +
	"\x11FleetModification\x12\x18\n" +
	"\afleetId\x18\x01 \x01(\x05R\afleetId\x12\x1a\n" +
	"\bsystemId\x18\x02 \x01(\x05R\bsystemId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x129\n" +
	"\vcomposition\x18\x04 \x01(\v2\x17.proto.FleetCompositionR\vcomposition\"m\n" +
	"\rFleetMovement\x12\x18\n" +
	"\afleetId\x18\x01 \x01(\x05R\afleetId\x12\"\n" +
	"\ffromSystemId\x18\x02 \x01(\x05R\ffromSystemId\x12\x1e\n" +
	"\n" +
	"toSystemId\x18\x03 \x01(\x05R\n" +
	"toSystemId\"\\\n" +
	"\fHealthUpdate\x12\x18\n" +
	"\afleetId\x18\x01 \x01(\x05R\afleetId\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x05R\x06health\x12\x1a\n" +
	"\bsystemId\x18\x03 \x01(\x05R\bsystemId\"\xae\x02\n" +
	"\vFleetUpdate\x12\x18\n" +
	"\afleetId\x18\x01 \x01(\x05R\afleetId\x12\x1a\n" +
	"\bsystemId\x18\x02 \x01(\x05R\bsystemId\x12\x1c\n" +
	"\tmaxHealth\x18\x03 \x01(\x05R\tmaxHealth\x12\x16\n" +
	"\x06health\x18\x04 \x01(\x05R\x06health\x12\x16\n" +
	"\x06attack\x18\x05 \x01(\x05R\x06attack\x12\x18\n" +
	"\aevasion\x18\x06 \x01(\x05R\aevasion\x12\x14\n" +
	"\x05armor\x18\a \x01(\x05R\x05armor\x12\x1a\n" +
	"\bexattack\x18\b \x01(\x05R\bexattack\x129\n" +
	"\vcomposition\x18\t \x01(\v2\x17.proto.FleetCompositionR\vcomposition\x12\x14\n" +
	"\x05owner\x18\n" +
	" \x01(\tR\x05owner\"F\n" +
	"\x0eFleetDestroyed\x12\x18\n" +
	"\afleetId\x18\x01 \x01(\x05R\afleetId\x12\x1a\n" +
	"\bsystemId\x18\x02 \x01(\x05R\bsystemId\"E\n" +
	"\x11SystemOwnerChange\x12\x1a\n" +
	"\bsystemId\x18\x01 \x01(\x05R\bsystemId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"M\n" +
	"\tGESUpdate\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x05R\x04rate\"\x92\x02\n" +
	"\rFleetCreation\x12\x1a\n" +
	"\bsystemId\x18\x01 \x01(\x05R\bsystemId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\afleetId\x18\x03 \x01(\x05R\afleetId\x12\x16\n" +
	"\x06attack\x18\x04 \x01(\x05R\x06attack\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x18\n" +
	"\aevasion\x18\x06 \x01(\x05R\aevasion\x12\x14\n" +
	"\x05armor\x18\a \x01(\x05R\x05armor\x12\x1a\n" +
	"\bexattack\x18\b \x01(\x05R\bexattack\x129\n" +
	"\vcomposition\x18\t \x01(\v2\x17.proto.FleetCompositionR\vcomposition\"%\n" +
	"\vGameVictory\x12\x16\n" +
	"\x06winner\x18\x01 \x01(\tR\x06winner2\x84\x01\n" +
	"\x04Game\x125\n" +
	"\bJoinGame\x12\x12.proto.JoinRequest\x1a\x13.proto.JoinResponse\"\x00\x12E\n" +
	"\x12MaintainConnection\x12\x18.proto.ConnectionRequest\x1a\x11.proto.GameUpdate\"\x000\x01B\x0fZ\rstarbit/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_service_proto_goTypes = []any{
	(*Empty)(nil),             // 0: proto.Empty
	(*JoinRequest)(nil),       // 1: proto.JoinRequest
	(*JoinResponse)(nil),      // 2: proto.JoinResponse
	(*ConnectionRequest)(nil), // 3: proto.ConnectionRequest
	(*Player)(nil),            // 4: proto.Player
	(*System)(nil),            // 5: proto.System
	(*GalaxyState)(nil),       // 6: proto.GalaxyState
	(*GameState)(nil),         // 7: proto.GameState
	(*GameUpdate)(nil),        // 8: proto.GameUpdate
	(*Fleet)(nil),             // 9: proto.Fleet
	(*FleetComposition)(nil),  // 10: proto.FleetComposition
	(*TickMsg)(nil),           // 11: proto.TickMsg
	(*FleetModification)(nil), // 12: proto.FleetModification
	(*FleetMovement)(nil),     // 13: proto.FleetMovement
	(*HealthUpdate)(nil),      // 14: proto.HealthUpdate
	(*FleetUpdate)(nil),       // 15: proto.FleetUpdate
	(*FleetDestroyed)(nil),    // 16: proto.FleetDestroyed
	(*SystemOwnerChange)(nil), // 17: proto.SystemOwnerChange
	(*GESUpdate)(nil),         // 18: proto.GESUpdate
	(*FleetCreation)(nil),     // 19: proto.FleetCreation
	(*GameVictory)(nil),       // 20: proto.GameVictory
	nil,                       // 21: proto.JoinResponse.PlayersEntry
	nil,                       // 22: proto.GameState.PlayersEntry
	nil,                       // 23: proto.GameUpdate.PlayersEntry
}
var file_proto_service_proto_depIdxs = []int32{
	21, // 0: proto.JoinResponse.players:type_name -> proto.JoinResponse.PlayersEntry
	6,  // 1: proto.JoinResponse.galaxy:type_name -> proto.GalaxyState
	9,  // 2: proto.System.fleets:type_name -> proto.Fleet
	5,  // 3: proto.GalaxyState.systems:type_name -> proto.System
	22, // 4: proto.GameState.players:type_name -> proto.GameState.PlayersEntry
	23, // 5: proto.GameUpdate.players:type_name -> proto.GameUpdate.PlayersEntry
	6,  // 6: proto.GameUpdate.galaxy:type_name -> proto.GalaxyState
	10, // 7: proto.Fleet.composition:type_name -> proto.FleetComposition
	13, // 8: proto.TickMsg.fleetMovements:type_name -> proto.FleetMovement
	14, // 9: proto.TickMsg.healthUpdates:type_name -> proto.HealthUpdate
	16, // 10: proto.TickMsg.fleetDestroyed:type_name -> proto.FleetDestroyed
	17, // 11: proto.TickMsg.systemOwnerChanges:type_name -> proto.SystemOwnerChange
	18, // 12: proto.TickMsg.gesUpdates:type_name -> proto.GESUpdate
	19, // 13: proto.TickMsg.fleetCreations:type_name -> proto.FleetCreation
	12, // 14: proto.TickMsg.fleetModifications:type_name -> proto.FleetModification
	15, // 15: proto.TickMsg.fleetUpdates:type_name -> proto.FleetUpdate
	20, // 16: proto.TickMsg.victory:type_name -> proto.GameVictory
	10, // 17: proto.FleetModification.composition:type_name -> proto.FleetComposition
	10, // 18: proto.FleetUpdate.composition:type_name -> proto.FleetComposition
	10, // 19: proto.FleetCreation.composition:type_name -> proto.FleetComposition
	4,  // 20: proto.JoinResponse.PlayersEntry.value:type_name -> proto.Player
	4,  // 21: proto.GameState.PlayersEntry.value:type_name -> proto.Player
	4,  // 22: proto.GameUpdate.PlayersEntry.value:type_name -> proto.Player
	1,  // 23: proto.Game.JoinGame:input_type -> proto.JoinRequest
	3,  // 24: proto.Game.MaintainConnection:input_type -> proto.ConnectionRequest
	2,  // 25: proto.Game.JoinGame:output_type -> proto.JoinResponse
	8,  // 26: proto.Game.MaintainConnection:output_type -> proto.GameUpdate
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
